# Generated by Django 5.0.6 on 2024-07-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primeapp', '0004_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
