# Generated by Django 5.0.6 on 2024-07-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeapp', '0008_mainsectionmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsectionmovie',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Action and Adventure'), (2, 'Comedy'), (3, 'Drama'), (4, 'Horror'), (5, 'Romance'), (6, 'Kids'), (7, 'Mystery and Thrillers')]),
        ),
    ]
