# Generated by Django 5.0.6 on 2024-07-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeapp', '0009_alter_mainsectionmovie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsectionmovie',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Action and Adventure'), (2, 'Comedy'), (3, 'Drama'), (4, 'Horror'), (5, 'Romance'), (6, 'Kids'), (7, 'Mystery and Thrillers'), (8, 'sci-fi')]),
        ),
    ]
