# Generated by Django 5.0.6 on 2024-07-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeapp', '0010_alter_mainsectionmovie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainsectionSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.IntegerField(choices=[(1, 'Award-Winning Tv Shows'), (2, 'Epic worlds'), (3, 'Exciting Tv shows'), (4, 'Horror')])),
                ('description', models.TextField(max_length=1000)),
                ('cover_image', models.ImageField(upload_to='media/')),
                ('video', models.FileField(upload_to='media/videos/')),
                ('season', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
