# Generated by Django 5.0.6 on 2024-07-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primeapp', '0012_alter_mainsectionseries_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainsectionseries',
            old_name='category',
            new_name='ratings',
        ),
    ]
