# Generated by Django 5.0.6 on 2024-07-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primeapp', '0016_remove_order_plan_remove_order_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
